### ISSUE TITLE
Loops on absolute paths

### ISSUE THREAD

**Issue by maximedenes** [LexiFi/dead_code_analyzer#8]
The analyzer loops on absolute paths (e.g. `dead_code_analyzer --references /tmp`) because of the path normalization function.

I'll submit a tentative fix.

**Comment by alainfrisch** [comment]
Fixed by #8.

**Comment by maximedenes** [comment]
I believe you mean "Fixed by #9". Is the fix correct on cygwin? It looks suspicious.

**Comment by alainfrisch** [comment]
Yes, indeed #9.

And indeed, the patch for this bug is suspicious, I'll look at it again.

**Comment by alainfrisch** [comment]
Does
````
  let rec split_path s =
    let open Filename in
    if s = current_dir_name || s = dirname s then [s]
    else (basename s) :: (split_path (dirname s))
  in
````
look right to you?

**Comment by maximedenes** [comment]
Yes, I've used that in the past as a termination condition for similar functions, I believe.
